export const LINKS = {
  linkedin: "https://www.linkedin.com/in/moaaz-akram/",
  behance: "https://www.behance.net/moaazalhajj",
  github: "https://github.com/xtcPanda",
  storyteller: "https://www.getstoryteller.com/",
  onepilot: "https://onepilot.co/",
  cooltra: "https://cooltra.com/",
};
export const ui = {
  en: {
    resume: "Résumé",
    enterRoom: "Open the studio",
    skipOpening: "Skip the opening",
    unboxWork: "Unpack the work desk",
    replayUnboxing: "Unpack it again",
    unpackComputer: "The MacBook Pro",
    unpackMonitors: "The two displays",
    unpackAccessories: "Keyboard, mouse and headset",
    unboxingReady: "Open a box. It knows where it belongs.",
    unboxingBusy: "Making room on the desk…",
    unboxingComplete: "Desk ready. Let’s see the work.",
    chapterList: "Chapters",
    chapterNext: "Next chapter",
    chapterPrev: "Previous chapter",
    reading: "Read at your own pace",
    returnToRoom: "Back to the studio",
    appearancePreview: "Appearance preview",
    forthcoming: "Coming later",
    personal: "Beyond the desk",
    future: "The someday list",
    name: "Moaaz Akram.",
    intro: "A few things on my mind.",
    intro2: "And on my desk.",
    sub: "Client delivery at Storyteller. Curious about what else can work.",
    try: "Try the Mac",
    explore: "Explore",
    connect: "Connect",
    language: "عربي",
    home: "Home",
    restart: "Restart",
    quick: "Just the work",
    story: "Comic",
    room: "Studio",
    canvas: "Project board",
    choose: "Two ways to look around.",
    chooseSub: "The studio, or the comic. Same work.",
    keep: "Back to my view",
    close: "Close",
    return: "Back to the studio",
    hint: "Drag to look around. Scroll to zoom. Open an object.",
    mobileHint: "Drag to look around. Pinch to zoom. Tap an object.",
    canvasHint: "Move the cards around. Open a project. A little order is optional.",
    tidy: "Tidy the board",
    read: "Read more",
    open: "Open",
    next: "Next stop",
    prev: "Previous stop",
    motion: "Camera motion",
    motionOn: "Camera motion on",
    motionOff: "Camera motion off",
    shot: "Hold to aim · release to shoot",
    shotKeys: "Hold Space, then release. Or hold the button.",
    score: "Baskets",
    shootAgain: "Try another shot",
    scored: "Nothing but net. Fine, mostly net.",
    missed: "Close. The windows were easier.",
    busy: "Ball in the air…",
    power: "Shot power",
    hoopTip: "A small detour from delivery. No meeting required.",
    fallback: "The studio couldn’t open here. The work is still below.",
    loading: "The work is ready. The studio is arriving.",
    viewLabel: "Choose how to explore",
    all: "All the work",
    project: "Project",
    notes: "Notes",
    minimise: "Minimise",
    simulation: "Browser simulation",
    planned: "Planned",
    prototype: "Prototype",
    completed: "Completed project",
    more: "More on LinkedIn",
    credits: "About this space",
    creditsBody:
      "An original interactive workbench. Built with Three.js; your choice of view stays on this device. No accounts, analytics or messages sent.",
    help: "Keyboard: use Explore to choose an object. Escape closes a window.",
    status: "Status",
    link: "Original work",
    newDemo: "2026 browser demo",
    quickIntro: "Client delivery at Storyteller, practical AI and a few things I’ve made.",
    quickTitle: "Moaaz, and the work.",
    role: "Client delivery & operations",
    shuffle: "Move things around",
    gallery: "Open the gallery",
    chapter: "Stop",
    of: "of",
  },
  ar: {
    resume: "السيرة الذاتية",
    enterRoom: "افتح الاستوديو",
    skipOpening: "عدّي المقدمة",
    unboxWork: "طلّع حاجات مكتب الشغل",
    replayUnboxing: "طلّعهم تاني",
    unpackComputer: "الـMacBook Pro",
    unpackMonitors: "الشاشتين",
    unpackAccessories: "الكيبورد والماوس والسماعة",
    unboxingReady: "افتح كرتونة. الحاجة عارفة مكانها.",
    unboxingBusy: "بنفضّي مكان على المكتب…",
    unboxingComplete: "المكتب جاهز. نشوف الشغل.",
    chapterList: "الفصول",
    chapterNext: "الفصل الجاي",
    chapterPrev: "الفصل اللي فات",
    reading: "اقرا براحتك",
    returnToRoom: "ارجع للاستوديو",
    appearancePreview: "معاينة الشكل",
    forthcoming: "جاي بعدين",
    personal: "بعيد عن المكتب",
    future: "قائمة يومًا ما",
    name: "معاذ أكرم.",
    intro: "كام حاجة على بالي.",
    intro2: "وعلى مكتبي.",
    sub: "شغل العملاء في Storyteller. وفضول ناحية إيه تاني ممكن ينفع.",
    try: "جرّب الماك",
    explore: "استكشف",
    connect: "نتواصل",
    language: "English",
    home: "الرئيسية",
    restart: "ابدأ من الأول",
    quick: "الشغل على طول",
    story: "الكوميكس",
    room: "الاستوديو",
    canvas: "لوحة المشاريع",
    choose: "طريقتين تتفرّج بيهم.",
    chooseSub: "الاستوديو أو الكوميكس. نفس الشغل.",
    keep: "ارجع لطريقتي",
    close: "اقفل",
    return: "ارجع للاستوديو",
    hint: "اسحب عشان تبص حواليك. حرّك العجلة للتكبير. افتح حاجة.",
    mobileHint: "اسحب عشان تبص حواليك. كبّر بصباعين. دوس على حاجة.",
    canvasHint: "حرّك الكروت. افتح مشروع. الترتيب اختياري شوية.",
    tidy: "رتّب اللوحة",
    read: "اقرا أكتر",
    open: "افتح",
    next: "المحطة الجاية",
    prev: "المحطة اللي فاتت",
    motion: "حركة الكاميرا",
    motionOn: "حركة الكاميرا شغّالة",
    motionOff: "حركة الكاميرا مقفولة",
    shot: "دوس مطوّل عشان تصوّب · سيب عشان ترمي",
    shotKeys: "دوس مطوّل على Space وسيبه. أو دوس على الزر.",
    score: "نقط",
    shootAgain: "جرّب رمية تانية",
    scored: "دخلت! طبعًا كان مقصود.",
    missed: "قريبة. ترتيب الشبابيك كان أسهل.",
    busy: "الكرة في الهوا…",
    power: "قوة الرمية",
    hoopTip: "استراحة صغيرة من الشغل. من غير اجتماع.",
    fallback: "الاستوديو مش متاح هنا. كل الشغل موجود تحت.",
    loading: "الشغل جاهز. والاستوديو في الطريق.",
    viewLabel: "اختار طريقة الاستكشاف",
    all: "كل الشغل",
    project: "مشروع",
    notes: "ملاحظات",
    minimise: "صغّر",
    simulation: "محاكاة في المتصفح",
    planned: "في الخطة",
    prototype: "نموذج أولي",
    completed: "مشروع خلص",
    more: "أكتر على لينكدإن",
    credits: "عن المكان ده",
    creditsBody:
      "مكتب تفاعلي بتصميم خاص، معمول باستخدام Three.js. اختيارك بيتحفظ على الجهاز ده. من غير حسابات أو تتبّع أو إرسال رسايل.",
    help: "بالكيبورد: افتح «استكشف» واختار حاجة. Escape بيقفل الشباك.",
    status: "الحالة",
    link: "الشغل الأصلي",
    newDemo: "ديمو متصفح ٢٠٢٦",
    quickIntro: "Client delivery في Storyteller، واستخدام عملي للـAI، وكام حاجة عملتها.",
    quickTitle: "معاذ، والشغل.",
    role: "شغل العملاء والعمليات",
    shuffle: "حرّك الحاجات",
    gallery: "افتح المعرض",
    chapter: "محطة",
    of: "من",
  },
};
export const projects = {
  tabs: {
    icon: "windows",
    image: "assets/tabs-icon-small.png",
    en: {
      title: "TABS",
      short: "The windows have assigned seats.",
      tag: "Functional Mac prototype · broader toolkit planned",
      body: "I built a native Mac prototype for saving and restoring window layouts, with a visual editor, saved layouts, manual restore and one-step Undo.",
      next: "Next: a modular Mac toolkit tailored to how I work, inspired by Vorssaint’s approach. That broader toolkit is still planned.",
      detail:
        "Try the idea with fictional windows below. This browser simulation doesn’t control your Mac.",
    },
    ar: {
      title: "TABS",
      short: "الشبابيك ليها أماكن محجوزة.",
      tag: "نموذج شغّال على الماك · الأدوات الأكبر لسه في الخطة",
      body: "عملت نموذج شغّال على الماك بيحفظ ترتيب الشبابيك ويرجّعه، بمحرّر مرئي وترتيبات محفوظة واسترجاع يدوي وتراجع بخطوة واحدة.",
      next: "اللي جاي: مجموعة أدوات للماك تناسب طريقة شغلي، مستوحاة من طريقة Vorssaint. الجزء الأكبر ده لسه في الخطة.",
      detail:
        "جرّب الفكرة بشبابيك افتراضية تحت. المحاكاة دي مش بتتحكم في الماك بتاعك.",
    },
    links: [
      {
        label: { en: "Toolkit direction reference", ar: "مرجع لاتجاه الأدوات" },
        url: "https://github.com/vorssaint/vorssaint-utils",
      },
    ],
  },
  haweshly: {
    icon: "coins",
    en: {
      title: "Haweshly / حوشلي",
      short: "First, let’s see where it went.",
      tag: "2024 database project · separate 2026 demo",
      body: "I built a personal finance database connecting accounts, transactions, savings goals and investments, with SQL reports for monthly income and expenses.",
      next: "حوشلي means “save my money for me” in Egyptian Arabic. The browser demo is a newer interface inspired by that database, built with Codex using fictional transactions.",
      detail:
        "Add a transaction, inspect the category report or export a month. Changes reset when the demo reloads; no bank connection or account.",
    },
    ar: {
      title: "حوشلي / Haweshly",
      short: "نشوف الفلوس راحت فين الأول.",
      tag: "مشروع قاعدة بيانات ٢٠٢٤ · ديمو منفصل ٢٠٢٦",
      body: "عملت قاعدة بيانات للفلوس بتربط الحسابات والمعاملات وأهداف الادخار والاستثمارات، وتقارير SQL للدخل والمصاريف الشهرية.",
      next: "حوشلي يعني «احفظ فلوسي عندك». ديمو المتصفح واجهة أحدث مستوحاة من قاعدة البيانات، عملتها بمساعدة Codex بمعاملات افتراضية.",
      detail:
        "ضيف معاملة، بص على تقرير الفئات، أو صدّر الشهر. التغييرات بتروح لما الديمو يعيد التحميل؛ من غير ربط ببنك أو حساب.",
    },
    links: [
      {
        label: {
          en: "Original project on LinkedIn",
          ar: "المشروع الأصلي على لينكدإن",
        },
        url: "https://www.linkedin.com/in/moaaz-akram/details/projects/",
      },
    ],
  },
  tourism: {
    icon: "globe",
    image: "assets/tourism-wireframes.webp",
    en: {
      title: "Tourism interface prototype",
      short: "“Where should we go?” is a bigger question than it sounds.",
      tag: "2020 team prototype",
      body: "I worked with the Light Seekers team during InnovEgypt on an early tourism app interface for discovering places through maps, information and video.",
      next: "We shared the prototype for feedback and qualified for the subsequent Ideathon stage. These are the original 2020 screens; my newer travel-planner idea is still deferred.",
      detail: "Explore the original screens on Behance.",
    },
    ar: {
      title: "نموذج واجهة للسياحة",
      short: "«نروح فين؟» طلعت سؤال أكبر مما كنت فاكر.",
      tag: "نموذج فريق ٢٠٢٠",
      body: "اشتغلت مع فريق Light Seekers في InnovEgypt على نموذج واجهة أولي لتطبيق سياحة، لاكتشاف الأماكن بالخرائط والمعلومات والفيديو.",
      next: "شاركنا النموذج عشان ناخد ملاحظات، واتأهلنا لمرحلة Ideathon اللي بعدها. دي الشاشات الأصلية من ٢٠٢٠؛ فكرة مخطّط السفر الجديدة لسه مؤجّلة.",
      detail: "شوف الشاشات الأصلية على Behance.",
    },
    links: [
      {
        label: {
          en: "Explore the original prototype",
          ar: "شوف النموذج الأصلي",
        },
        url: "https://www.behance.net/gallery/105016917/Innovegypt-",
      },
    ],
  },
  rfid: {
    icon: "circuit",
    en: {
      title: "RFID student prototype",
      short: "A check-in idea, before the school run.",
      tag: "University team prototype",
      body: "I worked with a university team on an RFID prototype, including system diagrams and parent/teacher interface designs for student check-ins and communication.",
      next: "Our presentation describes the proposed architecture, hardware/software choices and prototype plan. This is presented here as a university team prototype.",
      detail:
        "The original presentation shows the work and its scope. The browser simulation is a new illustration of the idea, with fictional check-ins.",
    },
    ar: {
      title: "نموذج RFID للطلبة",
      short: "فكرة لتسجيل حضور الطلبة والتواصل.",
      tag: "نموذج أولي مع فريق الجامعة",
      body: "اشتغلت مع فريق في الجامعة على نموذج RFID، ورسومات للنظام وواجهات للأهالي والمدرّسين لتسجيل حضور الطلبة والتواصل.",
      next: "العرض بيشرح المعمارية المقترحة واختيارات الأجهزة والبرامج وخطة النموذج. المعروض هنا هو نموذج أولي مع فريق الجامعة.",
      detail:
        "العرض الأصلي موضح الشغل ونطاقه. المحاكاة هنا شرح جديد للفكرة، بتسجيلات حضور خيالية.",
    },
    links: [
      {
        label: {
          en: "Open the original presentation",
          ar: "افتح العرض الأصلي",
        },
        url: "https://www.linkedin.com/in/moaaz-akram/overlay/1721228314810/single-media-viewer/?profileId=ACoAACiqe_IBG0Wl-ZN67rNjxDELNWK2Yz-eqGU",
      },
    ],
  },
  art: {
    icon: "frame",
    image: "assets/love-on-the-go.webp",
    en: {
      title: "Love on the Go",
      short: "A creative detour.",
      tag: "Personal illustration concept",
      body: "A personal Valentine’s illustration around Red Bull: warm colours, character composition and a playful brand idea.",
      next: "This is a personal portfolio concept, not commissioned client work or an endorsement.",
      detail:
        "Zoom into the illustration, then explore the variations on Behance.",
    },
    ar: {
      title: "Love on the Go",
      short: "لفة بعيد عن الشغل المعتاد.",
      tag: "فكرة رسمة شخصية",
      body: "رسمة شخصية لفالنتاين حوالين Red Bull: ألوان دافية وشخصيات وفكرة مرحة للبراند.",
      next: "دي تجربة شخصية للبورتفوليو، مش شغل بتكليف من البراند أو إعلان معتمد.",
      detail: "كبّر الرسمة، وشوف النسخ التانية على Behance.",
    },
    links: [
      {
        label: { en: "Artwork and variations", ar: "الرسمة والنسخ التانية" },
        url: "https://www.behance.net/gallery/219246973/Red-Bull-Valentines-Day-Illustration-Love-on-the-Go",
      },
    ],
  },
  articles: {
    icon: "notebook",
    en: {
      title: "A few things worth thinking about",
      short: "Work, motivation, and figuring things out.",
      tag: "My articles",
      body: "I write about work, communication and finding a direction. Some thoughts made it out of the notebook.",
      next: "Pick a cover to read the original article on LinkedIn.",
      detail: "",
    },
    ar: {
      title: "كام فكرة تستاهل نفكّر فيها",
      short: "الشغل والحماس ومحاولة نفهم إحنا رايحين فين.",
      tag: "مقالاتي",
      body: "بكتب عن الشغل والتواصل وإزاي ألاقي اتجاه. بعض الأفكار خرجت من الكشكول.",
      next: "اختار غلاف واقرا المقال الأصلي على لينكدإن.",
      detail: "",
    },
    links: [
      {
        label: { en: "All my articles", ar: "كل مقالاتي" },
        url: "https://www.linkedin.com/in/moaaz-akram/recent-activity/articles/",
      },
    ],
  },
  about: {
    icon: "person",
    en: {
      title: "Hi, I’m Moaaz.",
      short: "The work doesn’t all fit in one box. Conveniently, neither do I.",
      tag: "Client Delivery Operations at Storyteller",
      body: "I work in Client Delivery Operations at Storyteller: investigating product behaviour, clarifying requests and keeping the next steps useful. I also build tools, draw and play games. xtcpanda is my gaming nickname and appears in my line-art work.",
      next: "Based in Cairo. Start with the work desk or project board, then take a look around.",
      detail: "",
    },
    ar: {
      title: "أهلاً، أنا معاذ.",
      short: "شغلي مش كله في خانة واحدة. وأنا كمان.",
      tag: "Client Delivery Operations عند Storyteller",
      body: "بشتغل في Client Delivery Operations عند Storyteller: بحقق في سلوك المنتج، وبوضّح الطلبات والخطوات الجاية. وكمان بعمل أدوات وبرسم وبلعب. xtcpanda اسمي في الألعاب وبيظهر في شغل الـline art بتاعي.",
      next: "عايش في القاهرة. ابدأ بمكتب الشغل أو لوحة المشاريع، وبعدها اتفرّج حواليك.",
      detail: "",
    },
    links: [
      {
        label: { en: "Connect on LinkedIn", ar: "نتواصل على لينكدإن" },
        url: LINKS.linkedin,
      },
      {
        label: { en: "My work on Behance", ar: "شغلي على Behance" },
        url: LINKS.behance,
      },
    ],
  },
  work: {
    icon: "windows",
    en: {
      title: "The work desk",
      short: "A clearer request. A useful next step.",
      tag: "Client Delivery Operations at Storyteller · ongoing",
      body: "At Storyteller, I help turn unclear requests into practical delivery: checking product behaviour, documenting capabilities and keeping findings, blockers and next steps clear for the teams involved.",
      next: "I use practical AI to research and check the work, then keep the evidence, blockers and handoff clear. A confident answer still needs checking.",
      detail: "Open the work stories or résumé. The desk has enough screen space for the thing that still needs checking.",
    },
    ar: {
      title: "مكتب الشغل",
      short: "طلب أوضح. وخطوة جاية مفيدة.",
      tag: "Client Delivery Operations عند Storyteller · شغلي الحالي",
      body: "في Storyteller بساعد أحوّل الطلبات اللي لسه مش واضحة لخطوات تنفيذ: براجع سلوك المنتج، وبوثّق إمكانياته، وبخلّي النتايج والعوائق والخطوات الجاية واضحة للفرق المعنية.",
      next: "بستخدم AI في البحث والمراجعة، وبخلّي الأدلة والعوائق وتسليم الشغل واضحين. الإجابة الواثقة لسه محتاجة مراجعة.",
      detail: "افتح حكايات الشغل أو السيرة الذاتية. المكتب فيه مساحة كفاية للحاجة اللي لسه محتاجة مراجعة.",
    },
    links: [{ label: { en: "Storyteller", ar: "Storyteller" }, url: LINKS.storyteller }],
  },
  basketball: {
    icon: "hoop",
    en: {
      title: "A small basketball detour",
      short: "One more shot. A very reliable estimate.",
      tag: "Personal browser game",
      body: "A hoop, a ball and a quick break. Hold to aim, release to shoot, then see whether that confidence was justified.",
      next: "The score stays in this little game. Take another shot whenever you like.",
      detail: "You can also set the shot power with the slider and use the Shoot button.",
    },
    ar: {
      title: "استراحة باسكت صغيرة",
      short: "رمية كمان بس. تقدير دقيق جدًا للوقت.",
      tag: "لعبة شخصية في المتصفح",
      body: "سلة وكرة واستراحة سريعة. دوس مطوّل عشان تصوّب، سيب عشان ترمي، ونشوف الثقة دي كانت في محلها ولا لأ.",
      next: "النتيجة جوّه اللعبة الصغيرة دي. جرّب رمية تانية وقت ما تحب.",
      detail: "ممكن كمان تحدّد قوة الرمية بالشريط وتدوس على زر الرمي.",
    },
    links: [],
  },
};
export const workStories = {
  en: [
    {
      title: "Storyteller",
      body: "I investigate product behaviour, document capabilities and check AI-assisted workflows at Storyteller. I help teams make sense of requests and keep findings, blockers and next steps clear.",
    },
    {
      title: "Preply",
      body: "I built a NotebookLM knowledge base, a GPT support assistant and an Intercom categorisation system. The support team regularly used NotebookLM and GPT first, then Intercom. I also supported students and tutors and helped get issues to the people who could act on them.",
    },
    {
      title: "Amazon",
      body: "I helped a visually impaired customer update their payment method, following the same steps on my own computer so I could guide them clearly. They completed it without sharing their payment details. It became my First Smile story and was shared by managers.",
    },
    {
      title: "Kaedim",
      body: "I coordinated AI-assisted 3D production, assigned work to artists and reviewed assets against client briefs. I worked with engineering and leadership on quality gaps, priorities and production workflows.",
    },
    {
      title: "Onepilot",
      body: "From September to December 2025, I worked as a freelance KYC Officer through Onepilot. I reviewed submissions, flagged edge cases and maintained verification records.",
    },
  ],
  ar: [
    {
      title: "Storyteller",
      body: "في Storyteller بحقق في سلوك المنتج، وبوثّق إمكانياته، وبراجع الأدوات اللي فيها AI. بساعد الفرق تفهم الطلبات، وبخلّي النتايج والعوائق والخطوات الجاية واضحة.",
    },
    {
      title: "Preply",
      body: "عملت قاعدة معرفة على NotebookLM ومساعد دعم بـGPT ونظام تصنيف في Intercom. فريق الدعم استخدم NotebookLM وGPT بانتظام الأول، وبعدهم Intercom. وكمان ساعدت الطلبة والمدرّسين ووصلت المشاكل للي يقدروا يتصرفوا فيها.",
    },
    {
      title: "Amazon",
      body: "ساعدت عميل عنده إعاقة بصرية يحدّث طريقة الدفع. اتبعت نفس الخطوات على الكمبيوتر بتاعي عشان أقدر أوضّحها له، لحد ما خلّص من غير ما يديني بيانات الدفع. دي كانت أول «First Smile» ليا، والمديرين شاركوها.",
    },
    {
      title: "Kaedim",
      body: "نسّقت إنتاج أصول 3D بمساعدة AI، ووزّعت الشغل على الفنانين وراجعت الأصول على طلبات العملاء. واشتغلت مع الهندسة والإدارة على الجودة والأولويات وطريقة الإنتاج.",
    },
    {
      title: "Onepilot",
      body: "من سبتمبر لديسمبر ٢٠٢٥ اشتغلت فريلانس كـKYC Officer من خلال Onepilot. راجعت الطلبات، وعلّمت على الحالات اللي محتاجة مراجعة إضافية، وحافظت على سجلات التحقّق.",
    },
  ],
};
export const articles = [
  {
    image: "assets/writing/workplace-xp.png",
    en: "Workplace XP",
    ar: "اللعب والشغل",
    description: {"en": "On gamification at work.", "ar": "عن التلعيب في الشغل."},
    url: "https://www.linkedin.com/pulse/gamification-business-workplace-xp-moaaz-akram-i8fnf/",
  },
  {
    image: "assets/writing/career.png",
    en: "Still figuring it out",
    ar: "لسه بحاول أفهم",
    description: {"en": "On figuring out what I want to do.", "ar": "عن محاولة أفهم نفسي عايز أعمل إيه."},
    url: "https://www.linkedin.com/pulse/i-never-really-knew-what-wanted-moaaz-akram-1s3if",
  },
  {
    image: "assets/writing/direction.png",
    en: "Finding a direction",
    ar: "بلاقي اتجاه",
    description: {"en": "On finding a direction.", "ar": "عن إني ألاقي اتجاه."},
    url: "https://www.linkedin.com/pulse/finally-i-found-my-ikigai-moaaz-akram-rfwnf",
  },
  {
    image: "assets/writing/listening.png",
    en: "Sorry. You were saying?",
    ar: "معلش. كنت بتقول إيه؟",
    description: {"en": "On communication and being heard.", "ar": "عن التواصل وإن الكلام يوصل."},
    url: "https://www.linkedin.com/pulse/when-being-too-much-becomes-enough-moaaz-akram-lsrmf",
  },
  {
    image: "assets/writing/different.png",
    en: "Room to think differently",
    ar: "مساحة أفكّر بشكل مختلف",
    description: {"en": "On making room for different thinking.", "ar": "عن مساحة للتفكير بشكل مختلف."},
    url: "https://www.linkedin.com/pulse/challenge-being-different-why-thinking-outside-box-so-moaaz-akram-3opwf",
  },
  {
    image: "assets/writing/layoffs.png",
    en: "Layoffs changed how I see work",
    ar: "التسريح غيّر نظرتي للشغل",
    description: {"en": "On work, loyalty and layoffs.", "ar": "عن الشغل والولاء والتسريح."},
    url: "https://www.linkedin.com/pulse/more-than-just-number-what-layoffs-taught-me-work-loyalty-moaaz-akram-g9gwf",
  },
];

// These chapter IDs are shared by the guided, free-exploration and reading routes.
export const chapters = [
  { id: "welcome", station: "about", en: { title: "Moaaz, at the desk", lead: "Client delivery & operations at Storyteller. A clearer next step, with a little room for everything else." }, ar: { title: "معاذ، على المكتب", lead: "Client delivery & operations عند Storyteller. خطوة جاية أوضح، ومساحة لباقي الحاجات." } },
  { id: "make", station: "tabs", en: { title: "Make something", lead: "A Mac tool, a database, team prototypes, illustration and words. Things you can open, not just hear about." }, ar: { title: "نعمل حاجة", lead: "أداة للماك، وقاعدة بيانات، ونماذج مع فرق، ورسم وكلام. حاجات تقدر تفتحها وتشوفها." } },
  { id: "work", station: "work", en: { title: "At the work desk", lead: "Clearer requests, useful checks and the people behind the next step." }, ar: { title: "على مكتب الشغل", lead: "طلبات أوضح، ومراجعات مفيدة، والناس اللي ورا الخطوة الجاية." } },
  { id: "personal", station: "personal", en: { title: "Around the studio", lead: "Dusk, books, a favourite song, a few screens and a map with possibilities." }, ar: { title: "حوالين الاستوديو", lead: "Dusk وكتب وأغنية مفضّلة، وكام شاشة، وخريطة مليانة احتمالات." } },
  { id: "future", station: "future", en: { title: "The someday list", lead: "A few things to build. A few places to go. The list has clearly never met a calendar." }, ar: { title: "قائمة يومًا ما", lead: "كام حاجة أعملها، وكام مكان أروحه. واضح إن القائمة دي ما اتقابلتش مع تقويم قبل كده." } },
];

// A category uses the project copy shape. Items add concise, bilingual reading copy.
export const personalContent = {
  books: {
    icon: "notebook",
    en: { title: "On the shelf", short: "Some reading. Some rethinking.", tag: "Books", body: "I’m currently reading Think Again by Adam Grant. The shelf also has The Subtle Art of Not Giving a F*ck by Mark Manson and الأيام by Taha Hussein.", next: "No grand review yet. I’m still reading.", detail: "" },
    ar: { title: "على الرف", short: "شوية قراية. وشوية إعادة تفكير.", tag: "كتب", body: "بقرأ دلوقتي Think Again لآدم جرانت. وعلى الرف كمان The Subtle Art of Not Giving a F*ck لمارك مانسون، والأيام لطه حسين.", next: "لسه مفيش مراجعة كبيرة. أنا لسه بقرأ.", detail: "" },
    items: [
      { id: "think-again", en: { title: "Think Again — Adam Grant", body: "Currently reading." }, ar: { title: "Think Again — آدم جرانت", body: "بقرأه حاليًا." } },
      { id: "subtle-art", en: { title: "The Subtle Art of Not Giving a F*ck — Mark Manson", body: "On the shelf." }, ar: { title: "The Subtle Art of Not Giving a F*ck — مارك مانسون", body: "على الرف." } },
      { id: "al-ayam", en: { title: "الأيام — Taha Hussein", body: "On the shelf." }, ar: { title: "الأيام — طه حسين", body: "على الرف." } },
    ],
    links: [],
  },
  media: {
    icon: "windows",
    en: { title: "Play, watch, listen", short: "Not every screen needs a spreadsheet.", tag: "TV, games and listening", body: "The Mentalist was my first favourite TV show. House M.D., Dexter, Peaky Blinders, Friends, The King of Queens and How I Met Your Mother are in the mix too. Feeling Good by Michael Bublé is my number-one song.", next: "I’ve played PUBG, along with the games below. I also like Tony Stark / Iron Man, Cars and the teacher character in The Hangover. There’s room for a little range.", detail: "" },
    ar: { title: "ألعب وأتفرّج وأسمع", short: "مش كل شاشة محتاجة جدول.", tag: "مسلسلات وألعاب ومزيكا", body: "The Mentalist كان أول مسلسل مفضّل عندي. ومعاه House M.D. وDexter وPeaky Blinders وFriends وThe King of Queens وHow I Met Your Mother. وFeeling Good لمايكل بوبليه أغنيتي رقم واحد.", next: "لعبت PUBG، ومعاها الألعاب اللي تحت. وبحب Tony Stark / Iron Man وCars وشخصية المدرّس في The Hangover. فيه مساحة للتنوّع.", detail: "" },
    items: [
      { id: "tv", en: { title: "TV", body: "The Mentalist · House M.D. · Dexter · Peaky Blinders · Friends · The King of Queens · How I Met Your Mother" }, ar: { title: "المسلسلات", body: "The Mentalist · House M.D. · Dexter · Peaky Blinders · Friends · The King of Queens · How I Met Your Mother" } },
      { id: "games", en: { title: "Games", body: "PUBG · GTA · Mario · Snake · League of Legends · Valorant · Point Blank · Ghost Recon Phantoms · Uncharted · Inside · Assassin’s Creed Chronicles: China · Crash · pinball" }, ar: { title: "الألعاب", body: "PUBG · GTA · Mario · Snake · League of Legends · Valorant · Point Blank · Ghost Recon Phantoms · Uncharted · Inside · Assassin’s Creed Chronicles: China · Crash · pinball" } },
      { id: "favourite-song", en: { title: "Feeling Good — Michael Bublé", body: "My number-one song. Fair warning: it earns the replay." }, ar: { title: "Feeling Good — Michael Bublé", body: "أغنيتي رقم واحد. بتحب تتعاد، وأنا متعاون." } },
      { id: "listening", en: { title: "Also in the mix", body: "Shahyn · Cairokee · Khruangbin · Hania Rani" }, ar: { title: "بسمع كمان", body: "شاهين · Cairokee · Khruangbin · Hania Rani" } },
      { id: "screen-favourites", en: { title: "A few screen favourites", body: "Tony Stark / Iron Man · Cars · the teacher character in The Hangover" }, ar: { title: "كام حاجة بحبها على الشاشة", body: "Tony Stark / Iron Man · Cars · شخصية المدرّس في The Hangover" } },
    ],
    links: [{ label: { en: "Feeling Good — official music video", ar: "Feeling Good — الفيديو الرسمي" }, url: "https://www.michaelbuble.com/video/feeling-good-official-music-video-45541" }],
  },
  travel: {
    icon: "globe",
    en: { title: "Places, past and possible", short: "The map has a few open tabs too.", tag: "Background and travel wishes", body: "I was born in Saudi Arabia, live in Cairo now, and studied at Future University in Egypt in New Cairo. Tokyo and Disneyland are on the someday list.", next: "Vietnam is a tentative honeymoon idea for late 2026 or early 2027. The plan is still taking shape.", detail: "" },
    ar: { title: "أماكن من زمان وأماكن لبعدين", short: "الخريطة عليها شوية حاجات مفتوحة هي كمان.", tag: "منين جاي ونفسي أروح فين", body: "اتولدت في السعودية، وعايش في القاهرة دلوقتي، ودرست في جامعة المستقبل في مصر في القاهرة الجديدة. طوكيو وDisneyland في قائمة «يومًا ما».", next: "فيتنام فكرة مبدئية لشهر العسل في آخر ٢٠٢٦ أو أول ٢٠٢٧. الخطة لسه بتتكوّن.", detail: "" },
    items: [
      { id: "background", en: { title: "Saudi Arabia → Cairo", body: "Born in Saudi Arabia; based in Cairo now." }, ar: { title: "السعودية ← القاهرة", body: "اتولدت في السعودية؛ وعايش في القاهرة دلوقتي." } },
      { id: "tokyo", en: { title: "Tokyo and Disneyland", body: "Someday wishes." }, ar: { title: "طوكيو وDisneyland", body: "نفسي أروحهم يومًا ما." } },
      { id: "vietnam", en: { title: "Vietnam", body: "Tentative honeymoon idea, late 2026 or early 2027. Still planning." }, ar: { title: "فيتنام", body: "فكرة مبدئية لشهر العسل، آخر ٢٠٢٦ أو أول ٢٠٢٧. لسه بنخطّط." } },
      { id: "business-travel", en: { title: "A little further ahead", body: "A business that lets me travel the world, and the occasional business-class seat. An ambition for later." }, ar: { title: "أبعد شوية", body: "شغل خاص يخلّيني أسافر العالم، وكرسي بزنس كلاس من وقت للتاني. طموح لبعدين." } },
    ],
    links: [{ label: { en: "Future University in Egypt", ar: "جامعة المستقبل في مصر" }, url: "https://www.fue.edu.eg/" }],
  },
  food: {
    icon: "coins",
    en: { title: "A couple of food finds", short: "Saved for later. A familiar system.", tag: "Interesting finds", body: "Karak Boy and Barbar by D caught my eye in a couple of food posts. Here are the posts I saved.", next: "", detail: "" },
    ar: { title: "كام حاجة أكل لفتت نظري", short: "محفوظة لبعدين. نظام مألوف.", tag: "حاجات لفتت نظري", body: "Karak Boy وBarbar by D لفتوا نظري في كام بوست أكل. دي البوستات اللي حفظتها.", next: "", detail: "" },
    items: [],
    links: [
      { label: { en: "Saved food post — Adany’s Table", ar: "بوست أكل محفوظ — Adany’s Table" }, url: "https://www.instagram.com/adanys.table/reel/DVV5qpAAks1/" },
      { label: { en: "Saved food post — Morcos Cuisine", ar: "بوست أكل محفوظ — Morcos Cuisine" }, url: "https://www.instagram.com/morcos_cuisine/reel/DVjF1INjLqR/" },
    ],
  },
  ambitions: {
    icon: "globe",
    en: { title: "A fairly ambitious someday", short: "The wishlist is doing very well.", tag: "Wishes · not possessions or bookings", body: "A Harley, an iCAUR V27, a villa with a pool and a life there with my wife. I’d like to travel the world, try skydiving and maybe, one day, Everest.", next: "These are wishes. The garage, the pool and the mountain are all still on the someday side of the page.", detail: "" },
    ar: { title: "يومًا ما طموح شوية", short: "قائمة الأمنيات حالتها ممتازة.", tag: "أمنيات · لسه مش ممتلكات أو حجوزات", body: "هارلي وiCAUR V27، وفيلا بحمام سباحة وحياة فيها مع مراتي. نفسي أسافر العالم، وأجرّب القفز بالمظلات، ويمكن يومًا ما إيفرست.", next: "دي أمنيات. الجراج وحمام السباحة والجبل لسه كلهم في ناحية «يومًا ما» من الصفحة.", detail: "" },
    items: [],
    links: [],
  },
  ideas: {
    icon: "notebook",
    en: { title: "The idea shelf", short: "Names are easy. Building comes later.", tag: "Ideas · deferred", body: "A bigger Mac toolkit, a car-repair game, a magazine comic, a travel planner and a new business-card project. They’re ideas I’d like to build, alongside the other possibilities below. Names are considerably easier than finished products.", next: "Think Again also has me considering an article about mentality. The personal angle still needs finding.", detail: "" },
    ar: { title: "رف الأفكار", short: "الأسامي سهلة. التنفيذ بييجي بعدين.", tag: "أفكار · مؤجّلة", body: "مجموعة أدوات أكبر للماك، ولعبة إصلاح عربيات، وكوميكس لمجلة، ومخطّط سفر، ومشروع بيزنس كارد جديد. دي أفكار نفسي أعملها، ومعاها الاحتمالات اللي تحت. الأسامي أسهل بكتير من المشاريع اللي خلصت.", next: "Think Again كمان مخلّيني أفكّر في مقال عن طريقة التفكير. الزاوية الشخصية لسه محتاجة تتحدّد.", detail: "" },
    items: [
      { id: "mac-toolkit", en: { title: "A bigger Mac toolkit", body: "A planned toolkit beyond the existing TABS prototype." }, ar: { title: "أدوات أكبر للماك", body: "مجموعة أدوات في الخطة، أبعد من نموذج TABS الموجود." } },
      { id: "car-repair-game", en: { title: "A car-repair game", body: "A game idea. Still waiting for its first build." }, ar: { title: "لعبة إصلاح عربيات", body: "فكرة لعبة، لسه مستنية أول نسخة." } },
      { id: "magazine-comic", en: { title: "A magazine comic", body: "A comic idea I’d like to make." }, ar: { title: "كوميكس لمجلة", body: "فكرة كوميكس نفسي أعملها." } },
      { id: "business-card-project", en: { title: "A new business-card project", body: "An idea for later, separate from the existing Business Card artwork on Behance." }, ar: { title: "مشروع بيزنس كارد جديد", body: "فكرة لبعدين، منفصلة عن رسمة Business Card الموجودة على Behance." } },
      { id: "travel-planner", en: { title: "Hwa2alkFeen", body: "A newer travel-planner idea, deferred. It may revisit the question behind the 2020 tourism prototype; it is a separate idea." }, ar: { title: "Hwa2alkFeen", body: "فكرة أحدث لمخطّط سفر، مؤجّلة. ممكن أرجع بيها للسؤال ورا نموذج السياحة من ٢٠٢٠؛ لكنها فكرة منفصلة." } },
      { id: "remote-guide", en: { title: "Remote companies in Egypt", body: "A guide idea, deferred until I choose to take it forward." }, ar: { title: "شركات الشغل عن بُعد في مصر", body: "فكرة دليل مؤجّلة لحد ما أختار أكمّل فيها." } },
      { id: "memory-jewellery", en: { title: "Memory jewellery", body: "An idea I’d like to explore." }, ar: { title: "حُليّ للذكريات", body: "فكرة نفسي أستكشفها." } },
      { id: "chess", en: { title: "Something around chess", body: "An idea still taking shape." }, ar: { title: "حاجة حوالين الشطرنج", body: "فكرة لسه بتتكوّن." } },
      { id: "waste-pickup", en: { title: "Waste-pickup app", body: "An app idea, deferred." }, ar: { title: "تطبيق لجمع المخلفات", body: "فكرة تطبيق، مؤجّلة." } },
      { id: "mentality-article", en: { title: "A mentality article", body: "An article idea inspired by reading Think Again. Personal angle pending." }, ar: { title: "مقال عن طريقة التفكير", body: "فكرة مقال من قراية Think Again. الزاوية الشخصية لسه بتتحدّد." } },
    ],
    links: [],
  },
};

projects.personal = {
  icon: "person",
  en: { title: "Beyond the desk", short: "A few more things about me.", tag: "Personal", body: "I live with Dusk, my black cat, and have a Meta Quest 3 for another kind of screen time. Books, games and music have their own corners here too.", next: "The reading route has the shelf, the listening references, a couple of food finds and the places I’d like to go.", detail: "" },
  ar: { title: "بعيد عن المكتب", short: "كام حاجة تانية عنّي.", tag: "شخصي", body: "عايش مع Dusk، قطتي السودا، وعندي Meta Quest 3 لنوع تاني من وقت الشاشات. والكتب والألعاب والمزيكا ليهم ركنهم هنا كمان.", next: "في القراءة هتلاقي الرف، واللي بسمعهم، وكام حاجة أكل لفتت نظري، والأماكن اللي نفسي أروحها.", detail: "" },
  links: [],
};

// Optional scooter object: a brief assignment through Onepilot, not a direct role.
projects["kyc-bike"] = {
  icon: "circuit",
  en: { title: "A short KYC chapter", short: "Onepilot · September–December 2025", tag: "Freelance assignment through Onepilot", body: "I reviewed KYC submissions, flagged edge cases and maintained verification records during a short assignment through Onepilot.", next: "The scooter is a small reference to that assignment. The career chapter belongs to Onepilot.", detail: "" },
  ar: { title: "فصل KYC قصير", short: "Onepilot · سبتمبر–ديسمبر ٢٠٢٥", tag: "شغل فريلانس من خلال Onepilot", body: "راجعت طلبات KYC، وعلّمت على الحالات اللي محتاجة مراجعة إضافية، وحافظت على سجلات التحقّق في فترة قصيرة من خلال Onepilot.", next: "السكوتر إشارة صغيرة للفترة دي. فصل الشغل هنا عند Onepilot.", detail: "" },
  links: [
    { label: { en: "Onepilot", ar: "Onepilot" }, url: LINKS.onepilot },
    { label: { en: "Cooltra — assignment through Onepilot", ar: "Cooltra — الشغل من خلال Onepilot" }, url: LINKS.cooltra },
  ],
};
projects.future = {
  ...personalContent.ideas,
  en: { ...personalContent.ideas.en, title: "The someday list", body: `${personalContent.ideas.en.body} ${personalContent.ambitions.en.body}`, next: "The ideas are unbuilt; the travel, rides and home are wishes. A useful list, even before it becomes a plan." },
  ar: { ...personalContent.ideas.ar, title: "قائمة يومًا ما", body: `${personalContent.ideas.ar.body} ${personalContent.ambitions.ar.body}`, next: "الأفكار لسه ما اتعملتش؛ والسفر والعربيات والبيت أمنيات. قائمة مفيدة، حتى قبل ما تبقى خطة." },
};

projects.fishing = {
  icon: 'hoop',
  en: {title: 'One more catch', short: 'An original small fishing game.', tag: 'Browser mini-game · fictional arcade', body: 'An original fishing interaction for this portfolio, inspired by the arcade fishing games I enjoyed. Aim, cast and see what bites.', next: 'A new browser game, separate from the original arcade cabinet. No ROM or copied game assets.', detail: 'A 35-second round. No sign-in and no sound.'},
  ar: {title: 'سمكة كمان', short: 'لعبة صيد صغيرة وأصلية.', tag: 'لعبة للمتصفح · أركيد خيالي', body: 'لعبة صيد أصلية للبورتفوليو، فكرتها من ألعاب الصيد اللي كنت بحبها في الأركيد. اختار مكان الرمية، وارمي وشوف إيه هيمسك.', next: 'لعبة جديدة للمتصفح، منفصلة عن ماكينة الأركيد الأصلية. مفيش ROM ولا ملفات لعبة منسوخة.', detail: 'جولة ٣٥ ثانية. من غير تسجيل دخول ولا صوت.'},
  links: [],
};

personalContent.media.links.push({label:{en:'Listen to Feeling Good — Michael Bublé',ar:'اسمع Feeling Good — Michael Bublé'},url:'https://www.youtube.com/watch?v=Edwsf-8F3sI'});

ui.en.quick='Quick reading';ui.ar.quick='اقرا براحتك';
ui.en.all='Work stories & projects';ui.ar.all='حكايات الشغل والمشاريع';
ui.en.help='Drag to look around, scroll to zoom, or choose an object from Explore. Escape closes details.';
ui.ar.help='اسحب عشان تبص حواليك، وكبّر بالعجلة، أو اختار حاجة من «استكشف». Escape بيقفل التفاصيل.';
