// One professional record, with a presentation appropriate to each portfolio surface.
export const resumeRecord = {
 name:'Moaaz Akram',role:'Client delivery & operations',location:'Cairo, Egypt',
 lead:'I turn unclear requests into practical next steps, investigate product issues and help teams keep delivery moving.',
 summary:'My experience connects customer operations, AI-assisted 3D production and hands-on workflow building.',
 links:[{label:'LinkedIn',url:'https://www.linkedin.com/in/moaaz-akram/'},{label:'Portfolio',url:'https://xtcpanda.github.io/'}],
 jobs:[
 {company:'Storyteller',role:'Client Delivery Operations',date:'Jul 2026 - present',points:['Help clarify delivery requests, check product behaviour and document findings, blockers and next steps for the teams involved.','Use AI-assisted research and technical investigation to make product knowledge and operational checks easier to act on.']},
 {company:'FutureVersion',role:'Co-founder & COO',date:'Jun - Sep 2026',points:['Co-founded an early-stage AI and automation venture.']},
 {company:'Kaedim',role:'Production Manager (contract)',date:'Nov 2025 - Feb 2026',points:['Coordinated briefs, artists, priorities and reviews across AI-assisted 3D production, helping the teams involved work through dependencies and asset feedback.']},
 {company:'Preply',role:'Customer Support Specialist',date:'Feb - Dec 2025',points:['Handled customer support and helped connect colleagues and points of contact so issues could be acted on.','Built a NotebookLM knowledge base, GPT support assistant and Intercom categorisation workflow. The support team used the knowledge base and assistant first, then the Intercom workflow.']},
 {company:'Onepilot',role:'KYC Officer (freelance)',date:'Sep - Dec 2025',points:['Reviewed KYC submissions, flagged cases needing additional checks and maintained verification records.']},
 {company:'Amazon',role:'Account Specialist / Customer Service Representative',date:'May 2022 - Apr 2025',points:['Worked in customer service before moving into account support, investigating issues and guiding customers through next steps.','Helped a visually impaired customer update a payment method, following the same steps on my own computer; the interaction was recognised in a First Smile story.']}
 ],
 education:{school:'Future University in Egypt',date:'2018 - 2023',body:'Computer science studies; later major in Digital Media Technology.'},
 strengths:'Client communication · Cross-functional coordination · Product investigation · Knowledge management · Workflow design · Practical AI',
 tools:'NotebookLM · ChatGPT · Intercom · Airtable · Linear · SQL',languages:'Arabic: native · English: C2 proficient (EF SET, 78/100)'
};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy={en:{title:'Résumé',close:'Close résumé',download:'Download PDF',plain:'Plain PDF',english:'Résumé in English',theme:'Client delivery & operations',story:'Comic / career record',canvas:'Project board / résumé',room:'Studio / career record',profile:'Profile',experience:'Selected experience',education:'Education',strengths:'Practical strengths',tools:'Tools & languages',status:'English document · selectable text · PDF download',updated:'Current professional record',resumeLabel:'Moaaz Akram résumé'},ar:{title:'السيرة الذاتية',close:'اقفل السيرة الذاتية',download:'حمّل PDF',plain:'PDF بسيط',english:'السيرة الذاتية بالإنجليزي',theme:'Client delivery & operations',story:'الكوميكس / الخبرات',canvas:'لوحة المشاريع / السيرة الذاتية',room:'الاستوديو / الخبرات',profile:'نبذة',experience:'خبرات مختارة',education:'الدراسة',strengths:'مهارات عملية',tools:'الأدوات واللغات',status:'مستند إنجليزي · نص تقدر تنسخه · تحميل PDF',updated:'الخبرات المهنية الحالية',resumeLabel:'السيرة الذاتية لمعاذ أكرم'}};
const files={story:'assets/Moaaz-Akram-Resume-Story.pdf',canvas:'assets/Moaaz-Akram-Resume-Canvas.pdf',room:'assets/Moaaz-Akram-Resume-Room.pdf'};
export function mountResume(host,{lang='en',view='story',onOpen=()=>{},onClose=()=>{}}={}){
 if(!host?.ownerDocument)throw new TypeError('Résumé needs a host element.');
 const doc=host.ownerDocument,win=doc.defaultView,abort=new win.AbortController();let language=lang==='ar'?'ar':'en',selected=['story','canvas','room'].includes(view)?view:'story',opened=false,lastFocus;
 const dialog=doc.createElement('dialog');dialog.className='rv resume-view';dialog.setAttribute('aria-label',copy[language].resumeLabel);host.append(dialog);
 function render(){const scrollTop=dialog.querySelector('.rv__scroll')?.scrollTop||0;const c=copy[language],r=resumeRecord;dialog.dataset.view=selected;dialog.dataset.lang=language;
 dialog.innerHTML=`<div class="rv__window"><header class="rv__toolbar" dir="${language==='ar'?'rtl':'ltr'}"><div class="rv__toolbar-title"><span class="rv__traffic" aria-hidden="true"><i></i><i></i><i></i></span><span class="rv__document-glyph" aria-hidden="true">▤</span><strong>${esc(c.title)}</strong><span class="rv__toolbar-note">${esc(c[selected])}</span></div><button class="rv__close" aria-label="${esc(c.close)}" data-close>×</button></header><div class="rv__actions" dir="${language==='ar'?'rtl':'ltr'}"><span>${esc(c.english)}</span><div><a class="rv__download" href="${files[selected]}" download>${esc(c.download)} ↓</a><a href="assets/Moaaz-Akram-Resume-Plain.pdf" download>${esc(c.plain)} ↓</a></div></div><div class="rv__scroll"><article class="rv__paper" lang="en" dir="ltr" aria-label="Moaaz Akram professional record"><span class="rv__register" aria-hidden="true">CAREER / MOAAZ AKRAM</span><div class="rv__paper-head"><span class="rv__edition">${esc(copy.en[selected])}</span><h1>${r.name}</h1><p class="rv__role">${r.role}</p><div class="rv__contact"><span>${r.location}</span>${r.links.map(x=>`<a href="${x.url}" target="_blank" rel="noopener">${x.label} ↗</a>`).join('')}</div></div><section class="rv__section rv__section--profile"><h2>PROFILE</h2><div><p class="rv__lead">${esc(r.lead)}</p><p class="rv__summary">${esc(r.summary)}</p></div></section><section class="rv__section rv__section--experience"><h2>EXPERIENCE</h2><div>${r.jobs.map(job=>`<section class="rv__job"><div class="rv__job-head"><h3>${esc(job.company)}</h3><span>${esc(job.date)}</span></div><p class="rv__job-role">${esc(job.role)}</p><ul>${job.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section>`).join('')}</div></section><section class="rv__section"><h2>EDUCATION</h2><div><div class="rv__job-head"><h3>${r.education.school}</h3><span>${r.education.date}</span></div><p>${r.education.body}</p></div></section><section class="rv__section"><h2>STRENGTHS</h2><p>${esc(r.strengths)}</p></section><section class="rv__section"><h2>TOOLS & LANGUAGES</h2><div><p>${esc(r.tools)}</p><p>${esc(r.languages)}</p></div></section><footer class="rv__paper-foot"><span>Moaaz Akram / Client delivery & operations</span><span>CAREER RECORD</span></footer><span class="rv__selection-handle rv__selection-handle--tl" aria-hidden="true"></span><span class="rv__selection-handle rv__selection-handle--tr" aria-hidden="true"></span><span class="rv__selection-handle rv__selection-handle--bl" aria-hidden="true"></span><span class="rv__selection-handle rv__selection-handle--br" aria-hidden="true"></span></article></div><footer class="rv__status" dir="${language==='ar'?'rtl':'ltr'}"><span>${esc(c.status)}</span><span>${esc(c.theme)}</span></footer></div>`;
 dialog.setAttribute('aria-label',c.resumeLabel);dialog.querySelector('.rv__scroll').scrollTop=scrollTop;
 }
 function close(){if(!opened)return;opened=false;dialog.close();onClose();lastFocus?.focus?.({preventScroll:true});}
 function open(){if(!opened)lastFocus=doc.activeElement;opened=true;if(!dialog.open)dialog.showModal();dialog.querySelector('[data-close]')?.focus({preventScroll:true});onOpen();}
 dialog.addEventListener('click',e=>{if(e.target.closest('[data-close]'))close();else if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}},{signal:abort.signal});
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();},{signal:abort.signal});
 dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const all=[...dialog.querySelectorAll('button,a[href]')].filter(x=>!x.hidden);const first=all[0],last=all.at(-1);if(e.shiftKey&&doc.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&doc.activeElement===last){first.focus();e.preventDefault();}},{signal:abort.signal});
 render();return{open,close,setLanguage(next){language=next==='ar'?'ar':'en';render();if(opened)dialog.querySelector('[data-close]').focus({preventScroll:true});},setView(next){if(!['story','canvas','room'].includes(next))return;selected=next;render();if(opened)dialog.querySelector('[data-close]').focus({preventScroll:true});},destroy(){close();abort.abort();dialog.remove();}};
}
